Repository googleapis/nodejs-assured-workloads, pull requests merged in 2020-11, with the labels that each got.

#12 fix: do not modify options object, use defaultScopes
  .github/workflows/ci.yaml
  .jsdoc.js
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  linkinator.config.json
  package.json
  src/index.ts
  src/v1beta1/assured_workloads_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: assuredworkloads, automerge, cla: yes

#14 feat: added provisionedResourcesParent and kmsSettings
  protos/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: none

#19 fix: better fallback feature detection, linting, use optional chaining for window.fetch feature detection, mark window as global for linter
  protos/protos.json
  src/v1beta1/assured_workloads_service_client.ts
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: partial

#21 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: assuredworkloads, automerge, cla: yes, context: full
