Repository googleapis/nodejs-assured-workloads, pull requests merged in 2021-02, with the labels that each got.

#30 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: api: assuredworkloads, automerge, cla: yes

#31 chore: add UNORDERED_LIST to protos
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: none

#32 feat: updated google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService service. Clients can now create workloads with US_REGIONAL_ACCESS compliance regime
  protos/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: assuredworkloads, cla: yes, context: full
